[tool.black]
line-length = 125
target-version = ['py313']

[tool.isort]
profile = "black"
line_length = 125

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true
disallow_untyped_decorators = false
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = false
warn_no_return = true
warn_unreachable = true
strict_equality = true

# Allow dynamic attributes for pygame and game objects
[[tool.mypy.overrides]]
module = [
    "pygame.*",
    "numpy.*",
]
ignore_missing_imports = true

[tool.pylint.messages_control]
disable = [
    "too-many-arguments",
    "too-many-locals", 
    "too-many-branches",
    "too-many-statements",
    "too-few-public-methods",
    "global-statement",
    "invalid-name",
]

[tool.pylint.format]
max-line-length = 125 